
name: selecting snap
on:
  workflow_dispatch:
    inputs:
      SnapshotArns:
        description: 'select the snapshots ARN'
        default: 'Snapshot1'
        required: true
        type: choice
        options:
         - Snapshot1
         - Snapshot2
         - Snapshot3

jobs:
  Deploy:
    runs-on: ubuntu-latest
    #this is for control the deployment via approval method 1
    # alrerady craeted env with name dev in github setings 
    #environment: Infra

    
    steps:
     
    - name: Checkout
      uses: actions/checkout@v2


    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
       aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
       aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
       aws-region: us-east-1

        

    - name: "Deploying the snapshot1"
      if: ${{ github.event.inputs.SnapshotArns == 'Snapshot1' }}
      run: |
       snapshot1=`aws rds describe-db-snapshots --db-instance-identifier=database-1 --snapshot-type=manual --query="max_by(DBSnapshots, &SnapshotCreateTime).DBSnapshotArn" --output text`
       echo $snapshot1
       aws cloudformation deploy --stack-name dq-stack --template-file snap.yml --parameter-overrides DBSnapshotIdentifier=$snapshot1   

    - name: "deploying the snaphot2"
      if: ${{ github.event.inputs.SnapshotArns == 'Snapshot2' }}
      run: |
       snapshot3=`aws rds describe-db-snapshots --db-instance-identifier=database-1 --snapshot-type=manual --query="min_by(DBSnapshots, &SnapshotCreateTime).DBSnapshotArn" --output text`  
       echo $snapshot
       aws cloudformation deploy --stack-name dq-stack --template-file snap.yml --parameter-overrides DBSnapshotIdentifier=$snapshot   


   

       
